# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  dotnettemplate:
    image: dotnettemplate
    build:
      context: .
      dockerfile: DotnetTemplate/Dockerfile
    ports:
      - 8080:8080
